# Generated by Django 2.2.1 on 2019-06-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('thumb_nail', models.ImageField(blank=True, upload_to='static/img/projects')),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('technology', models.CharField(max_length=200)),
                ('deployed_url', models.CharField(blank=True, max_length=150, null=True)),
                ('github_url', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
