# Generated by Django 2.2.1 on 2019-06-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('thumb_nail', models.ImageField(blank=True, upload_to='uploads/static/img/projects')),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('deployed_url', models.CharField(blank=True, max_length=150, null=True)),
                ('github_url', models.CharField(blank=True, max_length=150, null=True)),
                ('technology', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('django', models.BooleanField(default=False)),
                ('javascript', models.BooleanField(default=False)),
                ('jquery', models.BooleanField(default=False)),
                ('react', models.BooleanField(default=False)),
                ('html', models.BooleanField(default=False)),
                ('css', models.BooleanField(default=False)),
                ('postgresql', models.BooleanField(default=False)),
                ('heroku', models.BooleanField(default=False)),
                ('aws', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
