# Generated by Django 2.2.1 on 2019-06-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='python',
            field=models.BooleanField(default=False),
        ),
    ]
