# Generated by Django 2.2.1 on 2019-06-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_icon',
            field=models.ImageField(blank=True, upload_to='static/img/projects'),
        ),
    ]
