# Generated by Django 2.2.1 on 2019-06-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_github_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_icon',
        ),
    ]
